[simulation]
input_folder_path = "/home/ambraser/Desktop/Stage/Code/R/data_simulation_2025/data_simu_UNI/"
data_path = "/home/ambraser/Desktop/Stage/Code/R/data_simulation_2025/data_simu_UNI/simu_UNI_v_101_c_14_i_693.csv"

#Data generation model 
generative_models = ["diversity", "uniform"]

# Voting methods to execute
rule_codes = ["AP_T", "AP_K", "BALD", "BLAC", "BORD", "CAIR", "CSUM", "CVIR", "BUCK_I", "BUCK_R", "COOM", "COPE", "DODG_C", "DODG_S", "EXHB", "HARE", "IRV", "IRVA", "IRVD", "ICRV", "KIMR", "L4VD", "MJ", "MMAX", "NANS", "PLU1", "PLU2", "RPAR", "RV", "SCHU", "SIRV", "SPCY", "STAR", "TIDE", "VETO", "WOOD", "YOUN"]
#rule_codes = ["AP_T", "AP_K", "BALD", "BLAC", "BORD", "CAIR", "CSUM", "CVIR", "BUCK_I", "BUCK_R", "COOM", "COPE", "DODG_C", "DODG_S", "EXHB", "HARE", "IRV", "IRVA", "IRVD", "ICRV", "KEME", "KIMR", "L4VD", "MJ", "MMAX", "NANS", "PLU1", "PLU2", "RPAR", "RV", "SCHU", "SIRV", "SLAT", "SPCY", "STAR", "TIDE", "VETO", "WOOD", "YOUN"]

# Numbers of candidates
candidates = [3,4,5,6,7,9,14]

# Numbers of voters
voters = [9,15,21,51,101,1001]

# Iterations numbers 
iterations = 1000

# seed 
seed = 42
